spring:
  datasource:
    # URL для подключения к твоей БД (замени hw2_db на имя своей базы)
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    # Аналог hibernate.dialect. Позволяет JPA "общаться" на языке PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Настройки Hibernate
    hibernate:
      # ddl-auto:
      # update - обновляет схему БД (добавляет колонки)
      # create-drop - создает таблицы при старте и удаляет при выходе (удобно для тестов)
      ddl-auto: update

    # Показывать ли SQL-запросы в консоли (удобно для отладки)
    show-sql: true
    properties:
      hibernate:
        format_sql: true